### ISSUE TITLE
Docker distribution?

### ISSUE THREAD

**Issue by vito** [hybris/bosh-init-deployment-resource#5]
[Concourse 0.74](https://concourse.ci/release-notes.html#v0.74.0) introduces [`resource_types`](https://concourse.ci/configuring-resource-types.html), making it much easier to consume third-party resources that are pushed to a Docker hub. Would you be opposed to publishing this there? Then people could use it by putting something like the following in their pipeline:

``` yaml
resource_types:
- name: bosh-init-deployment
  type: docker-image
  source: {repository: hybris/bosh-init-deployment-resource} # or wherever you put it
```

...which would be good to have somewhere prominent in the README as well.

I think this'll be a pretty good pattern for third-party Concourse resources to follow in general. Better would be to have some sort of a marketplace, but we don't have that yet.
